name: Ubuntu SSH Server  

on:  
  push:  
    branches:  
      - main  
  workflow_dispatch:  

jobs:  
  setup-ssh-server:  
    runs-on: ubuntu-22.04  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Install and configure SSH server  
        run: |  
          sudo apt update  
          sudo apt install -y openssh-server  
          sudo systemctl start ssh  
          sudo systemctl enable ssh  

          # Customize SSH configuration  
          echo "AllowUsers github-user" | sudo tee -a /etc/ssh/sshd_config  
          echo "Port 2222" | sudo tee -a /etc/ssh/sshd_config  
          sudo systemctl restart ssh  

      - name: Print SSH server details  
        run: |  
          echo "✅ SSH Server is set up on port 2222."  
          echo "🌐 Connect via: ssh -p 2222 github-user@<IP_Address>"  
